### ISSUE TITLE
CI: Deploy cron program to Cloudflare

### ISSUE THREAD

**Issue by EthanThatOneKid** [acmcsufoss/lc-dailies#17]
### Background
For continuous integration, we can automate the deployment of our daily cron program to Cloudflare via [`denoflare`](https://denoflare.dev). This is possible by combining GitHub workflows with `denoflare` via `deno task cf:push`.

### Sample `cf.yaml` workflow
```yaml
name: cf push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [canary]

    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Push to Cloudflare
        run: deno task cf:push
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
```

### Related

- #14
